#sudo: false
osx_image: xcode7.3

language: objective-c

before_install:
  # - gem install cocoapods # -v '0.37.2'
  - brew update
  - brew outdated xctool || brew upgrade xctool
  # - pod install
  # - xctool --version

# podfile: OpenHome/Podfile

branches:
only:
  - master

xcode_project: OpenHome.xcodeproj
xcode_scheme: OpenHome
xcode_sdk: iphonesimulator9.3

# script:
xctool -project OpenHome.xcodeproj -scheme OpenHome -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
