#sudo: false
osx_image: xcode7

language: objective-c

before_install:
  # - gem install cocoapods # -v '0.37.2'
  - brew update
  - brew outdated xctool || brew upgrade xctool
  # - pod install
  # - xctool --version

# podfile: OpenHome/Podfile

branches:
only:
  - master

xcode_project: OpenHome.xcodeproj
xcode_scheme: OpenHome
# script:
# - xctool -workspace OpenHome.xcworkspace -scheme OpenHome -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
